---
title: "CARICOM RBM"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Lothar Mateo Rojas Sosa"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
    number_sections: TRUE
    css: 
      before: "Style.css"

date: "`r format(Sys.time(), '%d %B %Y')`"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.align = 'center', echo = TRUE)

```

```{r data, include = FALSE}
library(readr)
library(tidyverse)
library(ggplot2)
library(readxl)

rm(try, try_0, try_1, try_4)

RBM <- read_excel("RBM_Dominica_1.xlsx")
RBM_ideal <- read_excel("RBM_ideal.xlsx")

RBM_ideal <- RBM_ideal %>%  
            mutate(  dimension = Dimension, dimension_d = case_when(  
              dimension == 1 ~  "Institutionalization",
              dimension == 2 ~ "Implementation",
              dimension == 3 ~ "Technical",
              dimension == 4 ~  "Use"
              ) ) %>% 
            select(-Dimension) %>% 
            select(dimension, dimension_d, bullet_id, sub_id, indicator)

RBM_full <- left_join(RBM,RBM_ideal)


try_1 <- RBM %>% 
        filter( bullet_id == 1)  %>% 
        filter(sub_id == 1)

try_4 <- RBM %>% 
        filter( bullet_id == 1)  %>% 
        filter(sub_id == 4)

try_0 <- RBM %>% 
        filter( bullet_id == 1)  %>% 
        filter(sub_id == 0)

```


```{r, results = 'asis' , echo = TRUE}

for ( i in 1:4){
  
  stage_1 <- RBM_ideal %>% 
            filter( dimension == i)
  
  cat(paste0( "# ", stage_1$dimension_d[1], " \n\n"))
  
  for( j in min(stage_1$bullet_id):max(stage_1$bullet_id)){
    
    
    stage_2 <- stage_1 %>% 
            filter( bullet_id == j)
    
    cat(paste0( "### ", filter(stage_2, sub_id == 0)$indicator[1], " {.tabset .tabset-pills} \n\n"))
    
    
    for( k in 1:max(stage_2$sub_id)){
      
      stage_3 <- RBM_full %>% 
            filter( dimension == i) %>% 
            filter( bullet_id == j) %>% 
            filter( sub_id == k)
      
      cat(paste0( "#### Sub-dimension  ",k, " {-} \n\n"))
      
      cat(paste0( " > ", stage_3$indicator[1]), "\n\n")
      
      cat(paste0("- ", stage_3$comment ), sep = "\n\n")
      cat("\n\n")
      
    }
    
    cat(paste0( "### {-}", " \n\n"))
    
    
  }
  
  
  
  
}


```



